version: '3'
services:

  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017
#    environment:
#      - MONGO-INIT_ROOT_USERNAME=user123
#      - MONGO-INIT_ROOT_PASSWORD=password123
    volumes:
      - mongo-data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    ports:
      - 8081:8081
    links:
      - mongodb
    environment:
#      - ME_CONFIG_MONGODB_ADMINUSERNAME=user123
#      - ME_CONFIG_MONGODB_ADMINPASSWORD=password123
      - ME_CONFIG_MONGODB_SERVER=mongodb

  spring-boot-mongodb-app:
    image: moonlight1996/spring-boot-mongodb-app:1.1
    container_name: spring-boot-mongodb-app
    restart: always
    ports:
      - 9090:8080
    links:
      - mongodb

volumes:
  mongo-data:
    driver: local
networks:
  default:
    name: spring-boot_mongodb_network