version: '3.1'
services:

  mongodb:
    image: mongo:latest
    volumes:
      - mongo-data:/data/db
    container_name: mongodb
    restart: always
    environment:
      MONGO-INIT_ROOT_USERNAME: user123
      MONGO-INIT_ROOT_PASSWORD: password123
#      - MONGO_INITDB_DATABASE=admin
    ports:
      - 27017:27017

  mongo-express:
    depends_on:
      - mongodb
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongodb
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: user123
      ME_CONFIG_MONGODB_ADMINPASSWORD: password123
      ME_CONFIG_MONGODB_SERVER: mongodb
    volumes:
      - mongo-data:/data/db

  spring-boot-mongodb-app:
    depends_on:
      - mongodb
    image: spring-boot-mongodb-app:1.1_auth
    container_name: spring-boot-mongodb-app
    restart: always
    ports:
      - 9090:8080
    links:
      - mongodb

volumes:
  mongo-data:
    driver: local
networks:
  default:
    name: spring-boot_mongodb_network